/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.errors;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ErrorEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2518320563309861940L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ErrorEvent\",\"namespace\":\"com.example.errors\",\"fields\":[{\"name\":\"errorId\",\"type\":\"string\",\"doc\":\"Unique error identifier\"},{\"name\":\"errorType\",\"type\":\"string\",\"doc\":\"Type of error\"},{\"name\":\"message\",\"type\":\"string\",\"doc\":\"Error message\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Error timestamp in milliseconds\"},{\"name\":\"details\",\"type\":[\"null\",\"string\"],\"doc\":\"Additional error details\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ErrorEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ErrorEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ErrorEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ErrorEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ErrorEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ErrorEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ErrorEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ErrorEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ErrorEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique error identifier */
  private java.lang.CharSequence errorId;
  /** Type of error */
  private java.lang.CharSequence errorType;
  /** Error message */
  private java.lang.CharSequence message;
  /** Error timestamp in milliseconds */
  private long timestamp;
  /** Additional error details */
  private java.lang.CharSequence details;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ErrorEvent() {}

  /**
   * All-args constructor.
   * @param errorId Unique error identifier
   * @param errorType Type of error
   * @param message Error message
   * @param timestamp Error timestamp in milliseconds
   * @param details Additional error details
   */
  public ErrorEvent(java.lang.CharSequence errorId, java.lang.CharSequence errorType, java.lang.CharSequence message, java.lang.Long timestamp, java.lang.CharSequence details) {
    this.errorId = errorId;
    this.errorType = errorType;
    this.message = message;
    this.timestamp = timestamp;
    this.details = details;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return errorId;
    case 1: return errorType;
    case 2: return message;
    case 3: return timestamp;
    case 4: return details;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: errorId = (java.lang.CharSequence)value$; break;
    case 1: errorType = (java.lang.CharSequence)value$; break;
    case 2: message = (java.lang.CharSequence)value$; break;
    case 3: timestamp = (java.lang.Long)value$; break;
    case 4: details = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'errorId' field.
   * @return Unique error identifier
   */
  public java.lang.CharSequence getErrorId() {
    return errorId;
  }


  /**
   * Sets the value of the 'errorId' field.
   * Unique error identifier
   * @param value the value to set.
   */
  public void setErrorId(java.lang.CharSequence value) {
    this.errorId = value;
  }

  /**
   * Gets the value of the 'errorType' field.
   * @return Type of error
   */
  public java.lang.CharSequence getErrorType() {
    return errorType;
  }


  /**
   * Sets the value of the 'errorType' field.
   * Type of error
   * @param value the value to set.
   */
  public void setErrorType(java.lang.CharSequence value) {
    this.errorType = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return Error message
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * Error message
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Error timestamp in milliseconds
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Error timestamp in milliseconds
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'details' field.
   * @return Additional error details
   */
  public java.lang.CharSequence getDetails() {
    return details;
  }


  /**
   * Sets the value of the 'details' field.
   * Additional error details
   * @param value the value to set.
   */
  public void setDetails(java.lang.CharSequence value) {
    this.details = value;
  }

  /**
   * Creates a new ErrorEvent RecordBuilder.
   * @return A new ErrorEvent RecordBuilder
   */
  public static com.example.errors.ErrorEvent.Builder newBuilder() {
    return new com.example.errors.ErrorEvent.Builder();
  }

  /**
   * Creates a new ErrorEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ErrorEvent RecordBuilder
   */
  public static com.example.errors.ErrorEvent.Builder newBuilder(com.example.errors.ErrorEvent.Builder other) {
    if (other == null) {
      return new com.example.errors.ErrorEvent.Builder();
    } else {
      return new com.example.errors.ErrorEvent.Builder(other);
    }
  }

  /**
   * Creates a new ErrorEvent RecordBuilder by copying an existing ErrorEvent instance.
   * @param other The existing instance to copy.
   * @return A new ErrorEvent RecordBuilder
   */
  public static com.example.errors.ErrorEvent.Builder newBuilder(com.example.errors.ErrorEvent other) {
    if (other == null) {
      return new com.example.errors.ErrorEvent.Builder();
    } else {
      return new com.example.errors.ErrorEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ErrorEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ErrorEvent>
    implements org.apache.avro.data.RecordBuilder<ErrorEvent> {

    /** Unique error identifier */
    private java.lang.CharSequence errorId;
    /** Type of error */
    private java.lang.CharSequence errorType;
    /** Error message */
    private java.lang.CharSequence message;
    /** Error timestamp in milliseconds */
    private long timestamp;
    /** Additional error details */
    private java.lang.CharSequence details;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.errors.ErrorEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.errorId)) {
        this.errorId = data().deepCopy(fields()[0].schema(), other.errorId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.errorType)) {
        this.errorType = data().deepCopy(fields()[1].schema(), other.errorType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.message)) {
        this.message = data().deepCopy(fields()[2].schema(), other.message);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.details)) {
        this.details = data().deepCopy(fields()[4].schema(), other.details);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ErrorEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.errors.ErrorEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.errorId)) {
        this.errorId = data().deepCopy(fields()[0].schema(), other.errorId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.errorType)) {
        this.errorType = data().deepCopy(fields()[1].schema(), other.errorType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.message)) {
        this.message = data().deepCopy(fields()[2].schema(), other.message);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.details)) {
        this.details = data().deepCopy(fields()[4].schema(), other.details);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'errorId' field.
      * Unique error identifier
      * @return The value.
      */
    public java.lang.CharSequence getErrorId() {
      return errorId;
    }


    /**
      * Sets the value of the 'errorId' field.
      * Unique error identifier
      * @param value The value of 'errorId'.
      * @return This builder.
      */
    public com.example.errors.ErrorEvent.Builder setErrorId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.errorId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'errorId' field has been set.
      * Unique error identifier
      * @return True if the 'errorId' field has been set, false otherwise.
      */
    public boolean hasErrorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'errorId' field.
      * Unique error identifier
      * @return This builder.
      */
    public com.example.errors.ErrorEvent.Builder clearErrorId() {
      errorId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorType' field.
      * Type of error
      * @return The value.
      */
    public java.lang.CharSequence getErrorType() {
      return errorType;
    }


    /**
      * Sets the value of the 'errorType' field.
      * Type of error
      * @param value The value of 'errorType'.
      * @return This builder.
      */
    public com.example.errors.ErrorEvent.Builder setErrorType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.errorType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'errorType' field has been set.
      * Type of error
      * @return True if the 'errorType' field has been set, false otherwise.
      */
    public boolean hasErrorType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'errorType' field.
      * Type of error
      * @return This builder.
      */
    public com.example.errors.ErrorEvent.Builder clearErrorType() {
      errorType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * Error message
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * Error message
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.example.errors.ErrorEvent.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.message = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * Error message
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'message' field.
      * Error message
      * @return This builder.
      */
    public com.example.errors.ErrorEvent.Builder clearMessage() {
      message = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Error timestamp in milliseconds
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Error timestamp in milliseconds
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.example.errors.ErrorEvent.Builder setTimestamp(long value) {
      validate(fields()[3], value);
      this.timestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Error timestamp in milliseconds
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Error timestamp in milliseconds
      * @return This builder.
      */
    public com.example.errors.ErrorEvent.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'details' field.
      * Additional error details
      * @return The value.
      */
    public java.lang.CharSequence getDetails() {
      return details;
    }


    /**
      * Sets the value of the 'details' field.
      * Additional error details
      * @param value The value of 'details'.
      * @return This builder.
      */
    public com.example.errors.ErrorEvent.Builder setDetails(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.details = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'details' field has been set.
      * Additional error details
      * @return True if the 'details' field has been set, false otherwise.
      */
    public boolean hasDetails() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'details' field.
      * Additional error details
      * @return This builder.
      */
    public com.example.errors.ErrorEvent.Builder clearDetails() {
      details = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ErrorEvent build() {
      try {
        ErrorEvent record = new ErrorEvent();
        record.errorId = fieldSetFlags()[0] ? this.errorId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.errorType = fieldSetFlags()[1] ? this.errorType : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.message = fieldSetFlags()[2] ? this.message : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.lang.Long) defaultValue(fields()[3]);
        record.details = fieldSetFlags()[4] ? this.details : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ErrorEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ErrorEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ErrorEvent>
    READER$ = (org.apache.avro.io.DatumReader<ErrorEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.errorId);

    out.writeString(this.errorType);

    out.writeString(this.message);

    out.writeLong(this.timestamp);

    if (this.details == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.details);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.errorId = in.readString(this.errorId instanceof Utf8 ? (Utf8)this.errorId : null);

      this.errorType = in.readString(this.errorType instanceof Utf8 ? (Utf8)this.errorType : null);

      this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);

      this.timestamp = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.details = null;
      } else {
        this.details = in.readString(this.details instanceof Utf8 ? (Utf8)this.details : null);
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.errorId = in.readString(this.errorId instanceof Utf8 ? (Utf8)this.errorId : null);
          break;

        case 1:
          this.errorType = in.readString(this.errorType instanceof Utf8 ? (Utf8)this.errorType : null);
          break;

        case 2:
          this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
          break;

        case 3:
          this.timestamp = in.readLong();
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.details = null;
          } else {
            this.details = in.readString(this.details instanceof Utf8 ? (Utf8)this.details : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










