/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.orders;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProcessedOrder extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3610462551076372043L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProcessedOrder\",\"namespace\":\"com.example.orders\",\"fields\":[{\"name\":\"orderId\",\"type\":\"string\",\"doc\":\"Unique order identifier\"},{\"name\":\"customerId\",\"type\":\"long\",\"doc\":\"Customer ID\"},{\"name\":\"status\",\"type\":\"string\",\"doc\":\"Order processing status\"},{\"name\":\"processedAt\",\"type\":\"long\",\"doc\":\"Processing timestamp in milliseconds\"},{\"name\":\"totalAmount\",\"type\":\"double\",\"doc\":\"Total order amount after processing\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProcessedOrder> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProcessedOrder> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProcessedOrder> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProcessedOrder> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProcessedOrder> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProcessedOrder to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProcessedOrder from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProcessedOrder instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProcessedOrder fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique order identifier */
  private java.lang.CharSequence orderId;
  /** Customer ID */
  private long customerId;
  /** Order processing status */
  private java.lang.CharSequence status;
  /** Processing timestamp in milliseconds */
  private long processedAt;
  /** Total order amount after processing */
  private double totalAmount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProcessedOrder() {}

  /**
   * All-args constructor.
   * @param orderId Unique order identifier
   * @param customerId Customer ID
   * @param status Order processing status
   * @param processedAt Processing timestamp in milliseconds
   * @param totalAmount Total order amount after processing
   */
  public ProcessedOrder(java.lang.CharSequence orderId, java.lang.Long customerId, java.lang.CharSequence status, java.lang.Long processedAt, java.lang.Double totalAmount) {
    this.orderId = orderId;
    this.customerId = customerId;
    this.status = status;
    this.processedAt = processedAt;
    this.totalAmount = totalAmount;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return customerId;
    case 2: return status;
    case 3: return processedAt;
    case 4: return totalAmount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.CharSequence)value$; break;
    case 1: customerId = (java.lang.Long)value$; break;
    case 2: status = (java.lang.CharSequence)value$; break;
    case 3: processedAt = (java.lang.Long)value$; break;
    case 4: totalAmount = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return Unique order identifier
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * Unique order identifier
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return Customer ID
   */
  public long getCustomerId() {
    return customerId;
  }


  /**
   * Sets the value of the 'customerId' field.
   * Customer ID
   * @param value the value to set.
   */
  public void setCustomerId(long value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return Order processing status
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * Order processing status
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'processedAt' field.
   * @return Processing timestamp in milliseconds
   */
  public long getProcessedAt() {
    return processedAt;
  }


  /**
   * Sets the value of the 'processedAt' field.
   * Processing timestamp in milliseconds
   * @param value the value to set.
   */
  public void setProcessedAt(long value) {
    this.processedAt = value;
  }

  /**
   * Gets the value of the 'totalAmount' field.
   * @return Total order amount after processing
   */
  public double getTotalAmount() {
    return totalAmount;
  }


  /**
   * Sets the value of the 'totalAmount' field.
   * Total order amount after processing
   * @param value the value to set.
   */
  public void setTotalAmount(double value) {
    this.totalAmount = value;
  }

  /**
   * Creates a new ProcessedOrder RecordBuilder.
   * @return A new ProcessedOrder RecordBuilder
   */
  public static com.example.orders.ProcessedOrder.Builder newBuilder() {
    return new com.example.orders.ProcessedOrder.Builder();
  }

  /**
   * Creates a new ProcessedOrder RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProcessedOrder RecordBuilder
   */
  public static com.example.orders.ProcessedOrder.Builder newBuilder(com.example.orders.ProcessedOrder.Builder other) {
    if (other == null) {
      return new com.example.orders.ProcessedOrder.Builder();
    } else {
      return new com.example.orders.ProcessedOrder.Builder(other);
    }
  }

  /**
   * Creates a new ProcessedOrder RecordBuilder by copying an existing ProcessedOrder instance.
   * @param other The existing instance to copy.
   * @return A new ProcessedOrder RecordBuilder
   */
  public static com.example.orders.ProcessedOrder.Builder newBuilder(com.example.orders.ProcessedOrder other) {
    if (other == null) {
      return new com.example.orders.ProcessedOrder.Builder();
    } else {
      return new com.example.orders.ProcessedOrder.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProcessedOrder instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProcessedOrder>
    implements org.apache.avro.data.RecordBuilder<ProcessedOrder> {

    /** Unique order identifier */
    private java.lang.CharSequence orderId;
    /** Customer ID */
    private long customerId;
    /** Order processing status */
    private java.lang.CharSequence status;
    /** Processing timestamp in milliseconds */
    private long processedAt;
    /** Total order amount after processing */
    private double totalAmount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.orders.ProcessedOrder.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.processedAt)) {
        this.processedAt = data().deepCopy(fields()[3].schema(), other.processedAt);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[4].schema(), other.totalAmount);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ProcessedOrder instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.orders.ProcessedOrder other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.processedAt)) {
        this.processedAt = data().deepCopy(fields()[3].schema(), other.processedAt);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[4].schema(), other.totalAmount);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * Unique order identifier
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * Unique order identifier
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.example.orders.ProcessedOrder.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * Unique order identifier
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * Unique order identifier
      * @return This builder.
      */
    public com.example.orders.ProcessedOrder.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * Customer ID
      * @return The value.
      */
    public long getCustomerId() {
      return customerId;
    }


    /**
      * Sets the value of the 'customerId' field.
      * Customer ID
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.example.orders.ProcessedOrder.Builder setCustomerId(long value) {
      validate(fields()[1], value);
      this.customerId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * Customer ID
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerId' field.
      * Customer ID
      * @return This builder.
      */
    public com.example.orders.ProcessedOrder.Builder clearCustomerId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * Order processing status
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * Order processing status
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.example.orders.ProcessedOrder.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * Order processing status
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'status' field.
      * Order processing status
      * @return This builder.
      */
    public com.example.orders.ProcessedOrder.Builder clearStatus() {
      status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'processedAt' field.
      * Processing timestamp in milliseconds
      * @return The value.
      */
    public long getProcessedAt() {
      return processedAt;
    }


    /**
      * Sets the value of the 'processedAt' field.
      * Processing timestamp in milliseconds
      * @param value The value of 'processedAt'.
      * @return This builder.
      */
    public com.example.orders.ProcessedOrder.Builder setProcessedAt(long value) {
      validate(fields()[3], value);
      this.processedAt = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'processedAt' field has been set.
      * Processing timestamp in milliseconds
      * @return True if the 'processedAt' field has been set, false otherwise.
      */
    public boolean hasProcessedAt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'processedAt' field.
      * Processing timestamp in milliseconds
      * @return This builder.
      */
    public com.example.orders.ProcessedOrder.Builder clearProcessedAt() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalAmount' field.
      * Total order amount after processing
      * @return The value.
      */
    public double getTotalAmount() {
      return totalAmount;
    }


    /**
      * Sets the value of the 'totalAmount' field.
      * Total order amount after processing
      * @param value The value of 'totalAmount'.
      * @return This builder.
      */
    public com.example.orders.ProcessedOrder.Builder setTotalAmount(double value) {
      validate(fields()[4], value);
      this.totalAmount = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'totalAmount' field has been set.
      * Total order amount after processing
      * @return True if the 'totalAmount' field has been set, false otherwise.
      */
    public boolean hasTotalAmount() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'totalAmount' field.
      * Total order amount after processing
      * @return This builder.
      */
    public com.example.orders.ProcessedOrder.Builder clearTotalAmount() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProcessedOrder build() {
      try {
        ProcessedOrder record = new ProcessedOrder();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.customerId = fieldSetFlags()[1] ? this.customerId : (java.lang.Long) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.processedAt = fieldSetFlags()[3] ? this.processedAt : (java.lang.Long) defaultValue(fields()[3]);
        record.totalAmount = fieldSetFlags()[4] ? this.totalAmount : (java.lang.Double) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProcessedOrder>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProcessedOrder>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProcessedOrder>
    READER$ = (org.apache.avro.io.DatumReader<ProcessedOrder>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.orderId);

    out.writeLong(this.customerId);

    out.writeString(this.status);

    out.writeLong(this.processedAt);

    out.writeDouble(this.totalAmount);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);

      this.customerId = in.readLong();

      this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);

      this.processedAt = in.readLong();

      this.totalAmount = in.readDouble();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);
          break;

        case 1:
          this.customerId = in.readLong();
          break;

        case 2:
          this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          break;

        case 3:
          this.processedAt = in.readLong();
          break;

        case 4:
          this.totalAmount = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










